# Destino: /etc/apache2/sites-available/flyweb.lamosquita.net.conf
# Página de FlyWeb (estática). Módulos: ssl, headers, http2. Requiere conf flyweb y flyweb-http.
<VirtualHost *:443>
    ServerName flyweb.lamosquita.net
    DocumentRoot "/srv/flyweb/www"
    Protocols h2 http/1.1
    SSLEngine on
    SSLProtocol -all +TLSv1.2 +TLSv1.3
    SSLCertificateFile    /etc/letsencrypt/live/flyweb/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/flyweb/privkey.pem

    Header always set Strict-Transport-Security "max-age=31536000"
    Header always set X-Content-Type-Options "nosniff"
    Header always set Content-Security-Policy "default-src 'self'"
    Header always set Referrer-Policy "no-referrer"

    CustomLog /var/log/flyweb/www-access.log flyweb_sinip
    ErrorLog  /var/log/flyweb/www-error.log
    ErrorLogFormat "[%{cu}t] [%-m:%l] %F: %E: %M"
    LogLevel warn

    <Directory "/srv/flyweb/www">
        Require method GET HEAD
    </Directory>
</VirtualHost>
